# Generated by Django 5.1.3 on 2026-03-22 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('korisnicko_ime', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Unesite validan broj telefona.', regex='^\\+?\\d{9,15}$')])),
                ('lozinka', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Korisnik',
                'verbose_name_plural': 'Korisnici',
            },
        ),
        migrations.CreateModel(
            name='Sat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='satovi/')),
            ],
        ),
        migrations.CreateModel(
            name='Porudzbina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('artikli', models.JSONField(help_text='Lista artikala u JSON formatu')),
                ('ukupno', models.IntegerField(help_text='Ukupna cena u RSD')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porudzbine', to='cloockot_watches.korisnik')),
            ],
            options={
                'verbose_name': 'Porudžbina',
                'verbose_name_plural': 'Porudžbine',
                'ordering': ['-datum'],
            },
        ),
    ]
