# Generated by Django 5.1.3 on 2025-10-29 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('korisnicko_ime', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Unesite validan broj telefona.', regex='^\\+?\\d{9,15}$')])),
                ('lozinka', models.CharField(max_length=128)),
            ],
        ),
    ]
