# Generated by Django 5.1.3 on 2026-04-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloockot_watches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porudzbina',
            name='naziv',
            field=models.CharField(blank=True, help_text='Naziv naručenog sata', max_length=200, null=True),
        ),
    ]
