# Generated by Django 5.1.3 on 2025-11-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloockot_watches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porudzbina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('artikli', models.JSONField()),
                ('ukupno', models.IntegerField()),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloockot_watches.korisnik')),
            ],
        ),
    ]
